version: '3.5'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
